return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c",
      "dockerfile",
      "go",
      "graphql",
      "html",
      "java",
      "javascript",
      "json",
      "jsonc",
      "jq",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "rust",
      "sql",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "xml",
    },
  },
}
